### ISSUE TITLE
Email Validator

### ISSUE THREAD

**Issue by OlPrognimak** [OlPrognimak/ordermanager#8]
Need to implement the email-validator and integrate into validable-input-text. Need to create new directive.

**Comment by PRYNSH1224** [comment]
Hey buddy, I would like to work on this issue!

**Comment by OlPrognimak** [comment]
You can do it, but i pay no money. That is research project which can produce anyway some invoice. Now invoice only in German.

**Comment by OlPrognimak** [comment]
@PRYNSH1224 You can do it, but i pay no money. That is research project which can produce anyway some invoice. Now invoice only in German.

**Comment by PRYNSH1224** [comment]
I

> @PRYNSH1224 You can do it, but i pay no money. That is research project which can produce anyway some invoice. Now invoice only in German.

I need no money , I only need your guidance .

**Comment by OlPrognimak** [comment]
@PRYNSH1224 I will think what to do. I create additional branch. I try to describe  how I expect implementation.
